name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '17 22 * * *'

env:
  OMP_NUM_THREADS: 2
    
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sblauth/docker_mwe:main

    steps:
    - name: Test installation
      run: |
        micromamba list
        which micromamba
        python -c "import numpy"
