name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '17 22 * * *'

env:
  OMP_NUM_THREADS: 2
    
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sblauth/docker_mwe:main

    steps:
    - name: Test installation
      shell: bash -l {0}
      run: |
        /usr/local/bin/_dockerfile_shell.sh micromamba list
        /usr/local/bin/_dockerfile_shell.sh which micromamba
        /usr/local/bin/_dockerfile_shell.sh python -c "import numpy"
